import Head from 'next/head'
import Image from 'next/image'
import { useContext } from 'react'
import { authContext } from '../context/UserContext'
import styles from '../styles/Home.module.css'
import  Login  from './login'
const RequireAuth = ({ children }) => {
  const { currentUser } = useContext(authContext);
  if (!currentUser) {
    return <Login />;
  }
  return children;
}

export default function Home() {
  return (
    <div className='bg-bg_color'>
      <Head>
        {/* here you can chage the title that appears in the tab bar */}
        <title>Bus Booking System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='h-auto w-auto'>
       <RequireAuth><Home/></RequireAuth>
      </main>
    </div>
  )
}
