import Head from 'next/head'
import Image from 'next/image'
import { useContext, useEffect } from 'react'
import { authContext, useAuthContext } from '../context/UserContext'
import styles from '../styles/Home.module.css'
import Login from './login'
import React, { useState } from "react";
import { auth } from "../firebase/firebase";
import { useRouter } from "next/router";
import Link from "next/link";
import LogoTrans from '../public/logo/classic_coast_logo_trans.svg'
import LoadingAnimaton from "../public/loading_anim.webp";

// const RequireAuth = ({ children }) => {
//   const router=useRouter()
//   const authContext=useAuthContext()
//   if (!authContext.currentUser) {
//     return <Login />;
//   }
//   return children;
// }

export default function Home() {
  const { currentUser, isUserLoading } = useAuthContext();
  const router = useRouter();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  const login = async () => {
    

    setIsLoading(true);
    auth.signInWithEmailAndPassword(email, password).then((authUser) => {
      console.log("Log in successful!");
      setIsLoading(false);
      router.push("/home");
      
    });
  };
  // useEffect(() => {
  //   if (isUserLoading && currentUser) {
  //     console.log('to home')
  //     router.push("/home");
  //   } 
  // }, [currentUser, isUserLoading]);

 if(isUserLoading){
   return <div className="flex flex-col items-center justify-center h-screen">
   <Image src={LoadingAnimaton} alt="Loading..." />
 </div>
 } else {
   return (
    <div className='bg-bg_color'>
      <Head>
        {/* here you can chage the title that appears in the tab bar */}
        <title>Bus Booking System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='h-auto w-auto'>
        <div className=" min-h-screen w-screen bg-bg_color">
      <div className="mx-auto w-64 h-48 overflow-hidden"><Image  src={LogoTrans} alt="Classic Coast Logo" /></div>
      
      <h1 className="text-dark_blue  font-khand font-bold text-center text-4xl">
        Log In
      </h1>
      <div className="flex flex-col space-y-10 w-1/4 mx-auto mt-10   ">
        <input
          onChange={(value) => {
            setEmail(value.target.value);
          }}
          className="bg-white text-black h-10 p-3 rounded-lg focus:outline-none"
          placeholder="Email"
        />
        <input
          onChange={(value) => {
            setPassword(value.target.value);
          }}
          className="bg-white text-black h-10 p-3 rounded-lg focus:outline-none"
          type="password"
          placeholder="Password"
        />
        <button
          onClick={login}
          className="border-4 bg-pink_red text-white p-2 w-3/4 mx-auto rounded-xl"
        >
          {isLoading ? "Loading..." : "Log In"}
        </button>
        {/* here the signup link */}
        <div className="flex space-x-2 mx-auto">
          <span className="text-dark_blue">{"Don't have an Account? "}</span>
          <Link href="/signup">
            <span className="text-pink_red underline cursor-pointer">
              Sign Up
            </span>
          </Link>
        </div>
      </div>
    </div>
      </main>
    </div>
  )
 }
}
